framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.apcu
        default_redis_provider: snc_redis.cache
        pools:
            doctrine.cache: null
        prefix_seed: packagist
