# In order to run packagist as docker containers
# install `docker` and `docker-compose` tool from:
# http://docs.docker.com/compose/install/
#
# After installation navigate to the local packagist repo
# and execute `docker-compose up` this will build the web
# image and download the redis, mysql and solr images in
# order to run the whole app.
#
# app/config/parameters.yml.docker is a sample file to use
# in this environment the only thing needed here are the github
# client id and secret
#
# app/config/config.yml.docker is the configuration to replace config.yml
# to support a solr external server
web:
    build: docker
    volumes:
        - .:/app
    ports:
        - "80:80"
    dns:
        - 8.8.8.8
        - 8.8.4.4
    links:
        - database
        - redis
        - solr

database:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: roots3cr3t
        MYSQL_DATABASE: packagist

redis:
    image: redis
    ports:
        - "6379:6379"

solr:
    image: apopelo/solr-3.6.2
    volumes:
        - ./doc/schema.xml:/opt/solr/example/solr/conf/schema.xml
    ports:
        - "8983:8983"
