version: '3'

services:
  php:
    build:
      context: docker/php
    working_dir: /var/www/packagist
    volumes:
      - .:/var/www/packagist
    depends_on:
      - mysql
      - redis
      - solr
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: packagist
  redis:
    image: redis:3.2
  solr:
    build:
      context: docker/solr
    environment:
      DEBUG: 'true'
      SOLR_VERSION: '3.6.0'
      SOLR_CONFS: '/etc/solr' 
