imports:
    - { resource: config_dev.yml }

parameters:
    database_name: %database_name_test%
    redis_dsn: %redis_dsn_test%

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
