parameters:
    packagist_host: ~
    packagist_metadata_dir: "%kernel.cache_dir%/composer-packages-build"
    session_save_path: %kernel.cache_dir%/sessions
    database_name_test: packagist_test
    redis_dsn_test: redis://127.0.0.1/14
