# See the Conductor setup guide at https://packagist.com/docs/conductor/getting-started

name: Private Packagist Conductor

on:
  repository_dispatch:
    types:
      - dependency_update

concurrency:
    group: ${{ github.workflow }}

permissions: {}

jobs:
  conductor:
    name: Private Packagist Conductor
    runs-on: ubuntu-24.04-arm

    permissions:
        contents: write # Allow Conductor to push commits with composer.json/.lock changes

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"

      # See the Conductor GitHub Action at https://github.com/packagist/conductor-github-action
      - name: "Running Conductor"
        uses: packagist/conductor-github-action@3513567296cf906ee3c97ba63df6f6d7ddcc55a5 # 1.6.1
