# See the Conductor setup guide at https://packagist.com/docs/conductor/getting-started

name: Private Packagist Conductor

on:
  repository_dispatch:
    types:
      - dependency_update

concurrency:
    group: ${{ github.workflow }}

permissions: {}

jobs:
  conductor:
    name: Private Packagist Conductor
    runs-on: ubuntu-24.04-arm

    permissions:
        contents: write # Allow Conductor to push commits with composer.json/.lock changes

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"

      # See the Conductor GitHub Action at https://github.com/packagist/conductor-github-action
      - name: "Running Conductor"
        uses: packagist/conductor-github-action@e19c62f9d97caff6166604942962597e412e01d8 # 1.6.0
