name: "PHP Lint"

on:
  - push
  - pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          coverage: "none"
          extensions: "intl"
          php-version: "8.4"

      - name: "Lint PHP files"
        run: "find src/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
