name: "PHPStan"

on:
  - push
  - pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  APP_ENV: dev
  DATABASE_URL: "mysql://root:root@127.0.0.1:3306/packagist?serverVersion=8.0"

permissions:
    contents: read

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          coverage: "none"
          extensions: "intl, zip, apcu"
          php-version: "8.4"
          tools: composer
          ini-values: apc.enable_cli=1

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          composer-options: "--ansi --no-interaction --no-progress --prefer-dist"

      - name: "Setup DB"
        run: |
          bin/console doctrine:database:create -n
          bin/console doctrine:schema:create -n

      - name: Run PHPStan
        run: composer phpstan
